name: CI/CD Pipeline for Budget Manager

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    env: # Define your environment variables here
      MONGODB_URI: "mongodb+srv://ericlasic12345:tR3tN2epjGtbbrmo@database.jcoom.mongodb.net/data?retryWrites=true&w=majority&appName=Database"
      JWT_SECRET: "UOJ9EBedTuyS9EsPZvDfw19jRrYN6J"
      EMAIL_USER: "dukenotest@gmail.com"
      EMAIL_PASS: "yhma jrzp rusj wxme"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Use the Node.js version required for your project

      - name: Install Dependencies
        run: |
          cd backend
          npm install

      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: '5.0'

      - name: Run Tests
        env:
          MONGODB_URI: mongodb://localhost:27017/testdb
        run: |
          cd backend
          npm test

      - name: Upload Coverage Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage-report
          path: backend/coverage # Adjust path to your coverage report directory

  frontend-tests:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Use the Node.js version required for your project

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Tests
        run: |
          cd frontend
          npm test

      - name: Upload Coverage Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage-report
          path: frontend/coverage # Adjust path to your coverage report directory
